// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/registry-sync.mjs

import SampleHero from "@registry/sample-hero";

export const REGISTRY_COMPONENTS = {
  "sample-hero": SampleHero,
} as const;

export type RegistryComponentName = keyof typeof REGISTRY_COMPONENTS;
