// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/registry-sync.mjs

import BuriosaCta01 from "@registry/buriosa-cta-01";
import BuriosaFaq01 from "@registry/buriosa-faq-01";
import BuriosaFeature01 from "@registry/buriosa-feature-01";
import BuriosaFooter01 from "@registry/buriosa-footer-01";
import BuriosaPricing01 from "@registry/buriosa-pricing-01";
import BuriosaTestimonial01 from "@registry/buriosa-testimonial-01";
import SampleHero from "@registry/sample-hero";

export const REGISTRY_COMPONENTS = {
  "buriosa-cta-01": BuriosaCta01,
  "buriosa-faq-01": BuriosaFaq01,
  "buriosa-feature-01": BuriosaFeature01,
  "buriosa-footer-01": BuriosaFooter01,
  "buriosa-pricing-01": BuriosaPricing01,
  "buriosa-testimonial-01": BuriosaTestimonial01,
  "sample-hero": SampleHero,
} as const;

export type RegistryComponentName = keyof typeof REGISTRY_COMPONENTS;
